spring:
  datasource:
    url: jdbc:mysql://192.168.1.128:3306/manager?${mysql-param}
    username: root
    password: 123456
  redis:
    # 服务器地址
    host: 192.168.1.128
    # 服务器连接端口
    port: 6379
    # 数据库索引 默认为0
    database: 0
    # Redis服务器连接密码 默认为空
    password: 123456
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
